use amazon;
select * from products;
select * from orders;
describe orders;
select * from order_items;

alter table orders
modify order_status varchar(20);


alter table order_items 
modify price_per_unit decimal(10,2);


CREATE INDEX idx_oi_product ON order_items(product_id);
CREATE INDEX idx_oi_order ON order_items(order_id);
CREATE INDEX idx_orders_status ON orders(order_status);



-- 1. Query the top 10 products by total sales value, including product name,
-- total quantity sold, and total sales value.
select 
	p.product_name, 
	round(sum(oi.quantity*oi.price_per_unit),2) as total_sales, 
    sum(quantity) as total_quantity from products p 
join order_items oi on p.product_id = oi.product_id
group by p.product_name
order by total_sales desc limit 10;

-- 2. Calculate total revenue generated by each product category and include
-- the percentage contribution of each category to total revenue.
select 
	c.category_name, p.product_name, 
	round(sum(oi.quantity * oi.price_per_unit),2) as revenue,
	concat(round((sum(oi.quantity * oi.price_per_unit)/sum(oi.price_per_unit))*100,2),'%') as percentage
from categories c 
join products p on c.category_id = p.category_id
join order_items oi on p.product_id = oi.product_id
group by c.category_name, p.product_name;

-- 3. Compute the average order value (AOV) for each customer and include
-- only customers with more than 5 orders.
select 
	c.customer_id,
    concat(c.first_name,' ',c.last_name) as customer_name,
    count(distinct o.order_id) as total_orders,
    round(sum(oi.quantity * oi.price_per_unit)/count(distinct o.order_id),2) as avg_order_value
from customers c 
join orders o on c.customer_id = o.customer_id
join order_items oi on o.order_id = oi.order_id
group by customer_id 
having count(distinct o.order_id) > 5;

select * from order_items;


-- 4. Query monthly total sales over the past year and display the current
-- month’s sales along with the previous month’s sales.

-- select date_format(o.order_date, '%Y-%m') as years_month,
-- sum(oi.quantity * oi.price_per_unit) as monthly_sales
-- from orders o 
-- join order_items oi 
-- 	on o.order_id = oi.order_id
-- where o.order_date >= date_sub(select max(order_date) from orders, interval 12 month)
-- group by years_month;
-- WITH monthly_sales AS (
-- SELECT
--     DATE_FORMAT(o.order_date, '%Y-%m-01') AS month_start,
--     SUM(oi.quantity * oi.price_per_unit) AS month_sales
--   FROM orders o
--   JOIN order_items oi ON oi.order_id = o.order_id
--   WHERE o.order_date >= (
--     SELECT DATE_SUB(MAX(order_date), INTERVAL 1 YEAR) FROM orders
--   )
--   GROUP BY DATE_FORMAT(o.order_date, '%Y-%m-01')
-- )
-- SELECT
--   cur.month_start AS month,
--   cur.month_sales AS current_month_sales,
--   prev.month_sales AS previous_month_sales
-- FROM monthly_sales cur
-- LEFT JOIN monthly_sales prev
--   ON prev.month_start = DATE_FORMAT(
--        DATE_SUB(cur.month_start, INTERVAL 1 MONTH),
--        '%Y-%m-01'
--      )
-- ORDER BY cur.month_start;

-- 5. Find customers who have registered but never placed an order, listing
-- customer details and the time since their registration.

select c.Customer_ID, concat(c.first_name,' ', c.last_name) as customer_name, o.order_id as number_of_orders from customers c  
left join orders o on c.customer_id = o.customer_id
where o.order_id is null;
-- order by o.order_id IS not NULL;

select count(*) from customers;
select count(distinct customer_id) from orders;


-- 6. Identify the least-selling product category for each state and include the
-- total sales for that category within each state.
with category_sales as (
select
	c.state,
    ct.category_name,
    sum(oi.quantity * oi.price_per_unit) as total_sales
from categories ct
join products p 
	on ct.category_id = p.category_id
join order_items oi 
	on p.product_id = oi.product_id
join orders o 
	on oi.order_id = o.order_id 
join customers c 
	on o.customer_id = c.customer_id 

group by c.state, ct.category_name
),
ranked_categories as (
	select 
		state,
        category_name,
        total_sales,
        row_number() over(partition by state order by total_sales asc) as rn
	from category_sales
)
select state, category_name, total_sales,rn
from ranked_categories
where rn = 1 
order by state;
 
select * from customers;

-- 7. Calculate the customer lifetime value (CLTV) for each customer and
-- rank customers based on their CLTV.
with customer_cltv as (
select 
	c.customer_id, 
	concat(c.first_name,' ',c.last_name) as customer_name, 
    o.order_status, 
    round(sum(oi.quantity * oi.price_per_unit),2) as CLTV
from customers c 
join orders o 
	on c.customer_id = o.customer_id 
join order_items oi 
	on o.order_id = oi.order_id
where o.order_status = 'Completed'
group by c.customer_id, customer_name
)

select 
	customer_id, 
    customer_name, 
    CLTV,
	dense_rank() over(order by cltv desc) as cltv_rank
from customer_cltv
order by cltv desc;


-- 8. Query products with stock levels below a certain threshold (e.g., less
-- than 10 units) and include the last restock date and warehouse
-- information.
SELECT 
    i.inventory_id,
    p.product_name,
    i.stock AS current_stock_left,
    i.last_stock_date,
    i.warehouse_id
FROM inventory i
JOIN products p
    ON p.product_id = i.product_id
WHERE i.stock < 10;

-- 9. Calculate the percentage of successful payments across all orders and
-- include a breakdown by payment status such as failed and pending.

select count(*) from payments;
select * from payments;

SELECT
    payment_status,
    COUNT(*) AS total_payments,
    ROUND(
        COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (),
        2
    ) AS percentage_of_total
FROM payments
GROUP BY payment_status
ORDER BY percentage_of_total DESC;

SELECT
    payment_status,
    COUNT(*) AS total_payments,
    ROUND(
        (COUNT(*)/ 
        (SELECT COUNT(*) FROM payments))*100.0,
        2
    ) AS percentage_of_total
FROM payments
GROUP BY payment_status
order by percentage_of_total desc;


-- 10. Query the top 10 products by the number of returns and display the
-- return rate as a percentage of total units sold for each product.
select 
    p.product_id,
    p.product_name,
    COUNT(*) as total_units_sold,
    SUM(case when o.order_status = 'Returned' then 1 else 0 end) AS total_returned,
    CAST(SUM(CASE WHEN o.order_status = 'Returned' then 1 else 0 end) as decimal(10,2)) 
        / CAST(COUNT(*) as decimal(10,2)) * 100 as return_percentage
from order_items oi
join products p 
    on oi.product_id = p.product_id
join orders o 
    on o.order_id = oi.order_id
group by 
    p.product_id, 
    p.product_name
order by 
    total_returned desc
limit 10;
-- Month-over-Month Revenue-Growth- > How is revenue changing month over month?

WITH monthly_sales AS (
    SELECT
        DATE_FORMAT(o.order_date, '%Y-%m') AS year_months,
        SUM(oi.quantity * oi.price_per_unit) AS revenue
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_status = 'Completed'
    GROUP BY year_months
)
SELECT
    year_months,
    revenue,
    LAG(revenue) OVER (ORDER BY year_months) AS prev_month_revenue,
    ROUND(
        (revenue - LAG(revenue) OVER (ORDER BY year_months)) * 100.0 /
        LAG(revenue) OVER (ORDER BY year_months),
        2
    ) AS growth_pct
FROM monthly_sales;

-- Top 20% Products contributing to Revenue 
with product_sales as (
select p.product_name, sum(oi.quantity*oi.price_per_unit) as revenue 
from products p 
join order_items oi on p.product_id = oi.product_id
join orders o on oi.order_id = o.order_id 
where o.order_status = 'Completed'
group by p.product_name
),
ranked as(
select *,
sum(revenue) over() as total_revenue,
sum(revenue) over(order by revenue desc) as cumulative_revenue
from product_sales
)
select * from ranked where cumulative_revenue <= total_revenue * 0.8;

-- Repeat vs One-Time Customers 

select c.Customer_Id, concat(c.first_name, ' ', c.last_name) as customer_name,
	case
		when count(o.order_id) > 1 then 'Repeat Customer'
        else 'One-Time Customer'
	end as customer_type
from customers c 
join orders o on c.Customer_ID = o.customer_id
group by o.customer_id;

-- Order with multiple payments attempts. 
SELECT
    order_id,
    COUNT(payment_id) AS payment_attempts
FROM payments
GROUP BY order_id
HAVING COUNT(payment_id) > 1;











